apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bhp
  name: bhp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bhp
    spec:
      containers:
      - image: bhp:tag
        name: bhp
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
