version: '2'

networks:
  my-network:

services:
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:tag
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - bhp
    

  bhp: 
    build:
      context: ./flask
      dockerfile: Dockerfile
    image: bhp:tag
    container_name: bhp
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my-network   
  



